config/routes.rb
Snapsplore::Application.routes.draw do
  get "users/show"

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }

  #get "/games", to: "bearded#faq", as: "faq"
  #get "/explore", to: "bearded#faq", as: "faq"

  get "/explore", to: "explore#index", as: "explore"
  get "/entries/full/:id", to: "entries#full", as: "full"
  get "/entries/explore/:id", to: "entries#explore", as: "explore_entry"
  get "/users/:id", to: "users#show", as: "show_user"
  resources :entries
  resources :list_items do 
    resources :entries
  end
  resources :games
  root to: "home#index"

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :user_id, :list_item_id, :image
  belongs_to :user
  belongs_to :list_item
  #belongs_to :game, through: :list_item

  mount_uploader :image, ImageUploader

  def image=(val)
    if !val.is_a?(String) && valid?
      image_will_change!
      super
    end
  end
  
end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :name, :description, :start_date, :end_date, :status
  has_many :list_items
  has_many :entries, through: :list_items

  def self.current
    #TODO: this is not accurate. Needs to search for a date range.
    Game.last
  end

  def to_param
    return "#{self.id}-#{self.name.parameterize}"
  end
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  attr_accessible :name, :flavor, :game_id
  belongs_to :game
  has_many :entries
  accepts_nested_attributes_for :entries
  #TODO: scope :current_game
  def to_param
    return "#{self.id}-#{self.name.parameterize}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :provider, :uid, :auth_token
  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :entries

  def to_param
    "#{self.id}-#{self.name.parameterize}"
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    
    # FB Won't give me email in production. Fine. We fake it.
    #puts "Auth Info Email: #{auth.info.email}"
    #puts "Auth Info Id: #{auth.uid}"

    email = auth.info.email
    email = "#{auth.uid}@facebook.com" if email.blank?
    if user
      return user
    else
      registered_user = User.where(:email => email).first
      if registered_user
        return registered_user
      else
        user = User.create!(name: auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:email,
                            password:Devise.friendly_token[0,20]
                          )
      end
    end
  end


  def solved(list_item)
    return "solved" if self.has_entered(list_item)
    return ""
  end

  def has_entered(list_item)
    return true if Entry.where(user_id:self.id, list_item_id: list_item.id).present?
    return false
  end

  def get_entry(list_item)
    return Entry.where(user_id:self.id, list_item_id: list_item.id).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_user

  def set_user
    if Rails.env.development?
      user = User.first
      sign_in user
    end
  end


end

app/controllers/bearded_controller.rb
class BeardedController < ApplicationController

  def index
    
  end

  def faq

  end


end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :get_list_item, except: [:full,:explore]
  before_filter :get_entry, except: [:full,:explore]

  def index

  end

  def show
    render "index"
  end

  def create
    @entry = Entry.new(params[:entry])
    @entry.image = params[:entry][:image]
    @entry.save
    render "index"
  end
  

  def update
    @entry = @entry || Entry.new(params[:entry])
    @entry.image = params[:entry][:image]
    @entry.save
    render "index"
  end

  def full
    @entry = Entry.find(params[:id])
    render layout: false
  end

  def explore
    @entry = Entry.find(params[:id])
  end
  
  protected

  def get_list_item
    @list_item = ListItem.find(params[:list_item_id])
  end

  def get_entry
    @entry = current_user.get_entry(@list_item)
    @entry = Entry.new if @entry.blank?
  end

end

app/controllers/explore_controller.rb
class ExploreController < ApplicationController

  def index
    #facebook_user = FbGraph::User.new('me', :access_token => session["fb_access_token"]).fetch
    #facebook_user.friends
    @users = User.all
    @entries = Game.current.entries
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    #TODO: this will eventually be "Game.current" or "Game.next"
    # figure out the game that's running / upcoming
    @game = Game.last
    redirect_to game_path(@game)
  end

  def show
    @game = Game.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end

  def faq

  end


end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController

  def index
    #TODO: @list_item = ListItem.current_game.all
    @list_items = ListItem.all
  end

  def show
    @list_item = ListItem.find(params[:id])
  end

  def update

  end
  
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def update
    @user = current_user
    @user.update_attribute(:name, params[:user][:name]) unless params[:user][:name].blank?
    @user.save
    flash[:success] = "Successfully changed display name!"
    redirect_to "/"
  end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def li_entry_path(li)
    return "#{list_item_path(li)}/entries"
  end
  
end

app/helpers/bearded_helper.rb
module BeardedHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/explore_helper.rb
module ExploreHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bearded/index.html.haml
.home
  %h1.colored.green
    Are YOU a Snapsplorer?
  .blog.content
    .post
      %h2=raw "Snap&bull;splore (v):" 
      .content
        %p 1) To boldly search for interesting and challenging sights, relate them tenuously to preselected categories, and share them with the world.
        %p 2) To find awesomeness wherever it may be and then steal its soul with your fancy device.
        %p 3) The game previously known as "Cell Phone Scavenger Hunt"
    .post
      %h2 Introduction
      .content
        %p You probably own a camera... maybe on your smartphone or feature phone. You probably like fun. If both of these apply, then you too can be a Snapsplorer! 
        %p
          %span Check out our
          %span
            %a{href:"/games"}launch game
          %span and get started on the fun!

app/views/entries/_form.html.haml
.form
  = simple_form_for [@list_item, @entry] do |e|
    %h3
      = @entry.image.url ? "can you do better?" : "what did you find?"
    .file-button.button.colored.orange Take a Photo
    .old-file-button
      = e.input :image, as: :file, input_html: {accept: "image/*;capture=camera", capture: "camera"}
    = e.input :user_id, as: :hidden, input_html: { value: "#{current_user.id}"}
    = e.input :list_item_id, as: :hidden, input_html: { value: "#{list_item.id}"}
    = e.button :submit, "Done -- Submit Photo!", class:"colored submit button hidden", style: "background:#009b2f;"

:css
  .old-file-button{display:none;}
  .file-button.button{text-align: center; cursor:pointer; width:50%;padding:10px;}

:javascript
  var interval = "";
  var intervalFunc = function () {
    if ($('.old-file-button input').val()) {
      //$(".file-button.button").attr("style","background: #009b2f;");
      //$(".file-button.button").html("Done!");
      $(".submit.button").removeClass("hidden");
      clearInterval(interval);
      $(".file-button.button").addClass("hidden");
    }
  };

  $('.submit.button').live("click" , function () {
    $(".overlay").removeClass("hidden");
    $(".modal").removeClass("hidden");
  });

  $('.file-button').live("click" , function () {
    $('.old-file-button input').click();
    interval = setInterval(intervalFunc, 50);
    return false;
  });

app/views/entries/explore.html.haml
.explore-entry
  %h3 #{@entry.user.name}'s entry
  %h1
    = "#{@entry.list_item.name}"
  - if @entry.list_item.flavor 
    %p
      = @entry.list_item.flavor
  .content
    - if @entry.image.show.url
      .image-entry
        %p (click image for full)
        %a{href: @entry.image.url, rel: "prettyPhoto"}
          = image_tag @entry.image.show.url
    .back
      = link_to "< Back to the Gallery", explore_path 

app/views/entries/full.html.haml
.full-entry
  = image_tag @entry.image.url

app/views/entries/index.html.haml
.entry
  - if @entry || @entry.user == current_user
    %h3 (your entry)
    %h1
      = "#{@list_item.name}"
    - if @list_item.flavor 
      %p
        = @list_item.flavor
    .content
      - if @entry.image.show.url
        .image-entry
          = link_to full_path(@entry) do
            = image_tag @entry.image.show.url
      = render partial: "form", locals: {list_item: @list_item, entry: @entry}
      .back
        = link_to "< Go Back to the List", games_path      
  - else
    %h3 (#{@entry.user.name}'s entry)
    %h1
      = "#{@list_item.name}"
    - if @list_item.flavor 
      %p
        = @list_item.flavor
    .content
      - if @entry.image.show.url
        .image-entry
          = image_tag @entry.image.show.url

app/views/explore/index.html.haml
%h1.colored.green Explore the Gallery
.content
  %ul.images
    - @entries.each do |entry|
      - unless entry.image.thumb.url.blank?
        %li.image 
          = link_to explore_entry_path(entry) do 
            .photo
              = image_tag entry.image.thumb.url
          .caption
            = link_to explore_entry_path(entry) do 
              .list-item #{entry.list_item.name}
            .author
              %a{href: "#{show_user_path(entry.user)}"} #{entry.user.name}
:javascript
  $(document).ready(function(){
    $("img").load(function(){
        var container = document.querySelector('.images');
        var msnry = new Masonry( container, {
          // options
          columnWidth: ".image",
          gutter: 10,
          itemSelector: '.image'
        }); 
    });
  });

app/views/games/show.html.haml
.display
  %h1.colored.green
    = @game.name
  .content
    .game
      %h2= raw "#{@game.start_date.strftime("%m/%d/%Y")} &mdash; #{@game.end_date.strftime("%m/%d/%Y")}"
      %p.description= @game.description
      - if current_user
        %ul
          - @game.list_items.each do |li|
            = link_to li_entry_path(li) do
              %li{class: "#{current_user.solved(li)}"}
                = li.name
      - else
        %p.running
          %span.warn This game is still running. Login to play!
        %p Check back when it's over to see all the entries, or log in with Facebook to join in the fun!

app/views/list_items/show.html.haml
.entry
  %h1
    = @list_item.name
  - if @list_item.flavor 
    %h2
      = @list_item.flavor
  .content

app/views/users/show.html.haml
%h1 #{@user.name}'s entries
.content
  %ul.images
    - @user.entries.each do |entry|
      - unless entry.image.thumb.url.blank?
        %li.image 
          = link_to explore_entry_path(entry) do 
            .photo
              = image_tag entry.image.thumb.url
          .caption
            = link_to explore_entry_path(entry) do 
              .list-item #{entry.list_item.name}
            .author
              %a{href: "#{show_user_path(entry.user)}"} #{entry.user.name}
:javascript
  $(document).ready(function(){
    $("img").load(function(){
        var container = document.querySelector('.images');
        var msnry = new Masonry( container, {
          // options
          columnWidth: ".image",
          gutter: 10,
          itemSelector: '.image'
        }); 
    });
  });