config/routes.rb
Snapsplore::Application.routes.draw do
  get "users/show"

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }

  #get "/games", to: "bearded#faq", as: "faq"
  #get "/explore", to: "bearded#faq", as: "faq"

  get "/explore", to: "explore#index", as: "explore"
  get "/entries/full/:id", to: "entries#full", as: "full"
  get "/entries/explore/:id", to: "entries#explore", as: "explore_entry"
  get "/users/:id", to: "users#show", as: "show_user"
  resources :entries
  resources :list_items do 
    resources :entries
  end
  resources :games
  root to: "home#index"

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :user_id, :list_item_id, :image
  belongs_to :user
  belongs_to :list_item
  #belongs_to :game, through: :list_item

  mount_uploader :image, ImageUploader

  def image=(val)
    if !val.is_a?(String) && valid?
      image_will_change!
      super
    end
  end
  
end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :name, :description, :start_date, :end_date, :status
  has_many :list_items
  has_many :entries, through: :list_items

  def self.current
    #TODO: this is not accurate. Needs to search for a date range.
    Game.last
  end

  def to_param
    return "#{self.id}-#{self.name.parameterize}"
  end
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  attr_accessible :name, :flavor, :game_id
  belongs_to :game
  has_many :entries
  accepts_nested_attributes_for :entries
  #TODO: scope :current_game
  def to_param
    return "#{self.id}-#{self.name.parameterize}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :provider, :uid, :auth_token
  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :entries

  def to_param
    "#{self.id}-#{self.name.parameterize}"
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    
    # FB Won't give me email in production. Fine. We fake it.
    #puts "Auth Info Email: #{auth.info.email}"
    #puts "Auth Info Id: #{auth.uid}"

    email = auth.info.email
    email = "#{auth.uid}@facebook.com" if email.blank?
    if user
      return user
    else
      registered_user = User.where(:email => email).first
      if registered_user
        return registered_user
      else
        user = User.create!(name: auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:email,
                            password:Devise.friendly_token[0,20]
                          )
      end
    end
  end


  def solved(list_item)
    return "solved" if self.has_entered(list_item)
    return ""
  end

  def has_entered(list_item)
    return true if Entry.where(user_id:self.id, list_item_id: list_item.id).present?
    return false
  end

  def get_entry(list_item)
    return Entry.where(user_id:self.id, list_item_id: list_item.id).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_user

  def set_user
    if Rails.env.development?
      user = User.first
      sign_in user
    end
  end


end

app/controllers/bearded_controller.rb
class BeardedController < ApplicationController

  def index
    
  end

  def faq

  end


end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :get_list_item, except: [:full,:explore]
  before_filter :get_entry, except: [:full,:explore]

  def index

  end

  def show
    render "index"
  end

  def create
    @entry = Entry.new(params[:entry])
    @entry.image = params[:entry][:image]
    @entry.save
    render "index"
  end
  

  def update
    @entry = @entry || Entry.new(params[:entry])
    @entry.image = params[:entry][:image]
    @entry.save
    render "index"
  end

  def full
    @entry = Entry.find(params[:id])
    render layout: false
  end

  def explore
    @entry = Entry.find(params[:id])
  end
  
  protected

  def get_list_item
    @list_item = ListItem.find(params[:list_item_id])
  end

  def get_entry
    @entry = current_user.get_entry(@list_item)
    @entry = Entry.new if @entry.blank?
  end

end

app/controllers/explore_controller.rb
class ExploreController < ApplicationController

  def index
    #facebook_user = FbGraph::User.new('me', :access_token => session["fb_access_token"]).fetch
    #facebook_user.friends
    @users = User.all
    @entries = Game.current.entries
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    #TODO: this will eventually be "Game.current" or "Game.next"
    # figure out the game that's running / upcoming
    @game = Game.last
    redirect_to game_path(@game)
  end

  def show
    @game = Game.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end

  def faq

  end


end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController

  def index
    #TODO: @list_item = ListItem.current_game.all
    @list_items = ListItem.all
  end

  def show
    @list_item = ListItem.find(params[:id])
  end

  def update

  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def li_entry_path(li)
    return "#{list_item_path(li)}/entries"
  end
  
end

app/helpers/bearded_helper.rb
module BeardedHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/explore_helper.rb
module ExploreHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Snapsplore
    %meta{name:"viewport", content:"width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body{class: "#{params[:controller]} #{params[:action]}"}
    .container
      .header
        = render 'shared/header'
        .notices
          = render 'shared/notices'
      .main
        .control
          = yield
      .overlay.hidden
      .modal.hidden
        %h2
          Uploading photo...
    .footer
      = render 'shared/footer'
    %script{type: "text/javascript", src:"//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-574e45ec5304dca1"}
    :javascript
      $(document).ready(function(){
        $("a[rel^='prettyPhoto']").prettyPhoto({
          social_tools: false,
          deeplinking:false,
          show_title:false,
          allow_resize:false,
          allow_expand:true
        });
      });
    :javascript
      $(document).ready(function(){
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-78645208-1', 'auto');
        ga('send', 'pageview');
      });

app/views/shared/_header.html.haml
.top
  .logo
    = link_to image_tag('/assets/snapsplore.png'), root_path
  = render 'shared/user'
.bottom
  = render 'shared/navigation'

app/views/shared/_navigation.html.haml
.navigation
  %ul
    %li.snap-link.current-game
      = link_to "Snap", games_path
    %li.explore-link
      = link_to "Explore", explore_path

app/views/shared/_user.html.haml
.user
  %ul
    %li.current-user
      - if user_signed_in?
        .sign-out.link
          = link_to "(Sign Out)", destroy_user_session_path, method: :delete
        .user-name.link
          = link_to current_user.name, edit_registration_path(current_user)
      -else
        .sign-in.link
          = link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)